# Generated by Django 4.2.6 on 2023-12-12 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_options_alter_productcategory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stripe_product_basket_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
